### PR TITLE
Feature/nav reorg

### PR DESCRIPTION
**Pull request by mitzimorris**
## Summary

Changed navigation titles per discussion with Breck and Matthijs.

To test this locally, check out this branch then run:

`bundle exec jekyll serve`

website will be available at `http://localhost:4000`

(assuming that you have the jekyll tools installed)

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Thanks for jumping in and reviewing.

There are multiple goals for the web site.  Matthijs's comments address some of the marketing side, mainly in terms of selling someone on Stan the language who doesn't already know about it/isn't already a user.

In terms of marketing, another great aspect of Stan is all the R tooling, in particular the visualizations, posterior analysis and packages like rstanarm and brms.  We have lots of users who'll never ever look at the language, for whom all of the example models and language doc are beside the point---they want to see examples of how to use brms or rstanarm.  

The other two groups of users we are currently trying to service with the web site are

* users who already use Stan

* developers who already use Stan

The current site's headers were an attempt to triage (biage?) these two sets of site visitors, without much attention paid to selling Stan.

The existing users primarily need to get new doc, new releases, etc., for whichever interface they're using.  They'd probably also like to see news up front, like whether there is a new release.

The devs need all the dev stuff which is spread all over wikis, Discourse, word-of-mouth, etc.  It might make sense to pull out a separate developer's site or just put everything for devs on wikis on GitHub or something so it doesn't confuse the user-facing site. 

You'll see the OCaml site is primarily aimed at users.  It's also much simpler in that it's just for the OCaml language.  Stan has the additional complication of interface language (R, Python, command-line, Julia, etc.), each of which has its own installation drill which breaks down by platform.  We also have official add-on packages like brms and rstanarm and loo.  If you look at R downloads, more of our users are using brms and rstanarm than are using rstan itself.

Maybe it'd make sense to break some of the interfaces out into their own site.  The advantage is that each site is simpler, but the disadvantage would be lack of common nav.  It's complicated when you deliver bunches of different things for different groups of people!

- Bob

**Comment by syclik** [comment]
@VMatthijs, are you not on the Website Committee list? That's where it should be happening.

**Comment by syclik** [comment]
@VMatthijs, you are on the email list. Let's discuss there.

**Comment by VMatthijs** [comment]
OK, thanks! I didn't realise you meant that E-mail chain.

**Pull request merged**
