### PR TITLE
Added hmm case study

### PR DESCRIPTION
**Pull request by bbbales2**
Adding an HMM case study!

### CODE REVIEW

**Comment by bbbales2** [comment]
Here's the example model pull request with discussion: https://github.com/stan-dev/example-models/pull/187

**Comment by bbbales2** [comment]
@serban-nicusor-toptal does the error here look like a problem with my pull or CI? I see this error: https://travis-ci.com/github/stan-dev/stan-dev.github.io/builds/197896607 , which doesn't seem like an error with the stuff I added

**Comment by serban-nicusor-toptal** [comment]
There was a bug in the Travis configuration that was fixed on master, this PR must have forked from the old broken version of it.
See [old](https://github.com/stan-dev/stan-dev.github.io/blob/1280d905920a9531e8abc4241aaa051bc2eea42c/.travis.yml) versus [new](https://github.com/stan-dev/stan-dev.github.io/blob/master/.travis.yml).
Can you please change the contents of `.travis.yml` to those in the master branch ? That will solve the issue. Thanks!

**Comment by bbbales2** [comment]
@serban-nicusor-toptal thanks it worked!

@mitzimorris ready for review!

**Comment by bbbales2** [comment]
@charlesm93 can you review this?

**Comment by charlesm93** [comment]
Looks good to me. You're missing some dependencies. The total list should be: `tidyverse`, `ggplot2`, `cmdstanr`, and `posterior`. Fix that and you should be good to merge.

**Comment by bbbales2** [comment]
@charlesm93 1.5 months later, ready for review lol

**Comment by charlesm93** [comment]
No worries, I realize how busy you are. I'll go through it today.

**Comment by bbbales2** [comment]
Should just be this change: https://github.com/stan-dev/stan-dev.github.io/pull/130/commits/24a6e5f18dfbc1881987e8513c0947510cf1a662

~~busy~~ -> forgetful

**Comment by charlesm93** [comment]
Looks good to me. Feel free to go ahead and merge.

**Pull request merged**
