### PR TITLE
shinyStan --> ShinyStan

### PR DESCRIPTION
**Pull request by jgabry**
Update names: interface is now ShinyStan and R package is shinystan.

### CODE REVIEW

**Comment by jgabry** [comment]
Ok I think that's everything.

**Comment by jgabry** [comment]
Can this be merged? The new version was accepted by CRAN, so in a day or so the website will be out of date.

**Comment by bob-carpenter** [comment]
Whenever it makes sense is fine by me.

- Bob

**Comment by jgabry** [comment]
Ok, looks like I don't have write access to the repo so someone else will need to actually merge it.

**Comment by syclik** [comment]
I merged it. @jgabry, you should have permissions now.

**Pull request merged**
