### PR TITLE
Split out images and static assets from case studies

### PR DESCRIPTION
**Pull request by aaronjg**
Currently, the case studies have all of the images, and several megabytes of external javascript libraries built into them. This causes load and render times to be several seconds.

By splitting them up, we can reduce this time substantially since:

- rendering can begin as soon as the .html file is downloaded
- javascripts libraries can be cached between requests
- the web browser can download multiple embedded images simultaneously

I did not update:
- pool-binary-trials-rstanarm.html
- radon.html
- tutorial_twopl.html

Since I could not find the original source for the first two, and the last one no longer compiles due to underlying library changes.

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Wow.  That was a lot of work.  I like the organization into directories.  

@betanalpha: are you OK with this change?

@jgabry or @bgoodri : is there a repo for the case study on hierarchical models?  

@aaronjg:  Is it faster?

The source for the radon example is in Jupyter, not knitr, and it's on @fonnesbeck's repo:

https://github.com/fonnesbeck/stan_workshop_2016/blob/master/notebooks/Multilevel%20Modeling.ipynb

What went wrong with the other model?  Other than no longer allowing `lp__`, everything should be backward compatible in Stan programs.  Or is it an issue with rstan or another library?

**Comment by betanalpha** [comment]
This is going to make it more annoying to manage the case
studies and update them whenever there are changes.  Were
this split off into another repo that we could link to from mc-stan
I’d be more inclined, but right now I’m worried about the looming
maintenance burden.

**Comment by aaronjg** [comment]
@bob-carpenter Once I figured out all the dependent libraries I needed, it was pretty straightforward to build everything. I've had some sporadic downtime as I've been waiting for my stan models to run :)

*Backwards Compatability* For the tutorial_twopl.html, they had built a library on top of stan, and then changed the function signatures so it no longer worked. I was really impressed that all the other models ran without needing any modification. 

*Performance* For the divergence case study it new version takes 670ms until DOMContentLoad and 1.5 seconds total, old version takes 9 s to DOM load and 9.3 s total.

To get a sense for the feel of it you can compare:
https://aaronjg.github.io/stan-dev.github.io/users/documentation/case-studies/divergences_and_bias.html

to:
http://mc-stan.org/users/documentation/case-studies/divergences_and_bias.html
If you have visited the page before may need to to a ctrl-f5 refresh to see how long it would take for a new visitor.

*Organization* I agree with @betanalpha, there should be a good way to maintain these going forward. I think there could be a case studies repository that can then be included as a submodule into both the example repository and the site repository. If it is set up correctly, you can just run "markdown::render_site('.')" from R and it will build the whole thing from scratch.

**Comment by betanalpha** [comment]
Moving forwards, if we’re going to split everything out into
separate files then I think we need to push everything to
a separate case studies repo.  That will also require someone
to be responsible for maintaining it as well as some policy
for deciding what gets added to it.   Unfortunately we’ve
hit a wall where we’re either going to make it a pain to
maintain the current website or significantly increase 
the logistics around case studies.

**Comment by aaronjg** [comment]
This pull request doesn't seem like that much more work since it is now just one file + one accompanying directory. Adding new case studies could be done by just dropping them into the directory. Then again, I'm just using the website and not dealing with maintaining it 

If you go to having a separate repo and with the case study source and ability to compile them all, then it is more work to maintain, on the plus side the user can easily find all the data needed to run the examples, and you can easily identify when case studies break do to library issues like in the [Two-Parameter Logistic Item Response Model](http://mc-stan.org/users/documentation/case-studies/tutorial_twopl.html).

**Comment by betanalpha** [comment]
Yes, what we’d really want to do is have people check in their raw
Rmd (with any necessary aux files) and have a global make script
that calls knitr on any files that have changed.  Then we can hook 
in CI to ensure that the markdown files knit successfully and get
into a proper PR process.

But that’s also the problem — we’re at that precipice where going
forward would be a significant maintenance burden.  It would be
awesome, just not something we have time for at the moment.

Any volunteers?

**Comment by mitzimorris** [comment]
spring cleaning - is this still relevant or should it be closed?

**Comment by aaronjg** [comment]
Fine with me to either merge or reject. Changes proposed by @betanalpha will be too much work so if required to merge, better to just keep as is.

**Pull request closed without merging**
