### PR TITLE
small fix

### PR DESCRIPTION
**Pull request by randommm**
just a missing `span` tag

### CODE REVIEW

**Comment by bob-carpenter** [comment]
How'd it get past the validity checkers without the span tag?  We should validate all the pages to make sure there aren't more issues like this.

**Comment by randommm** [comment]
I don't know why it doesn't show up here: https://validator.w3.org/nu/?doc=http%3A%2F%2Fmc-stan.org%2Fdocumentation%2F

**Comment by bob-carpenter** [comment]
Here's the problem:

	<a href="http://www.stat.columbia.edu/~gelman/book/software.pdf">Appendix C: Computation in R and Stan</a>↩
	class=”note”&gt;(stat.columbia.edu)&lt;/span&gt;↩
	<br />↩

You can see that whatever Jekyll did mangled the tags so they're
no longer ill-formed tags, just a bunch of escapes (&lt; and gt;)
with quotes replaced with curly quotes.  So the result isn't ill-formed
HTML, just not what we intended there.

It also looks like Jekyll's generating some non-compliant HTML
according to the validator --- probably targeted at MS's usual
mess of non-compliance, like a cleartype tag.

- Bob

**Comment by randommm** [comment]
I see, I didn't inspected the source code, just spotted the typo and fixed directly here.

**Pull request merged**
