### PR TITLE
Add new case study on plant interactions

### PR DESCRIPTION
**Pull request by Cristinabarber**
Hello, I would like to add this case study on how the segment function from Stan can overcome inefficiencies caused by sparse matrices in plant interactions models.

### CODE REVIEW

**Comment by jgabry** [comment]
Awesome, thanks for the pull request! Since I know you already got feedback on this over email I'm going to go ahead and merge this now instead of waiting for someone to review it.

**Comment by Cristinabarber** [comment]
Thanks a lot!!!

**Comment by jgabry** [comment]
Something didn't work quite right. It's listed now at https://mc-stan.org/users/documentation/case-studies but clicking on the link to the html doesn't work. I'll take a look and see if I can fix it.

**Comment by Cristinabarber** [comment]
Hi Jonah, I was about to write to you about it. I was looking at the
case-study.md and I am not very sure what I did wrong. I appreciate a lot
your help.

**Comment by jgabry** [comment]
Ok I figured it out. Should be working now. The issue was that the html file was in the folder `documentation/case-studies` instead of `users/documentation/case-studies`. I moved it and I think it's ok now. I didn't realize the first location existed. I think it must be some old folder we don't use anymore. Sorry for the confusion.

**Comment by Cristinabarber** [comment]
Ups!! Thanks a lot! and sorry for the confusion!

**Comment by jgabry** [comment]
No worries, I didn't realize we had another case-studies folder that was outdated or I would have warned you about it ;) Thanks again for the case study!

**Comment by Cristinabarber** [comment]
Ups!! Thanks a lot! and sorry for putting it in the wrong place. I am
checking and I still cannot see the HTML, but maybe it is taking a bit to
update

**Pull request merged**
