### PR TITLE
Correcting some typos in the plant interactions case study 

### PR DESCRIPTION
**Pull request by Cristinabarber**

### CODE REVIEW

**Comment by syclik** [comment]
@Cristinabarber, I think the change is fine, but GitHub won't allow this to be merged. There are git conflicts that need to be resolved first.

**Comment by syclik** [comment]
Can you let me know when you fix the git conflicts?

**Comment by Cristinabarber** [comment]
Hi Daniel,

I am going to close the pull request and I send the new version of the HTML
that I wanted to add to Jonah Gabry so he con upload it to the repository.
Sorry for the inconvenience and thanks for the help.

Best,
Cristina

**Comment by jgabry** [comment]
Thanks @Cristinabarber. I'm not sure why this created conflicts if just the html was changed (I don't think it was changed anywhere else that could conflict with this), but now that I have the html I'll see if I can figure it out.

**Pull request closed without merging**
