### PR TITLE
Documentation generated for docs-2-25

### PR DESCRIPTION
**Pull request by serban-nicusor-toptal**
This is a documentation change.

## Summary

Updating site references to docs version 2.25

## Context

https://github.com/stan-dev/math/issues/2128

### CODE REVIEW

**Review by mitzimorris — APPROVED** [review]
lgtm!

**Comment by mitzimorris** [comment]
@serban-nicusor-toptal - travis is unhappy - can't install the Ruby(?) toolchain needed to build the docs.

**Comment by serban-nicusor-toptal** [comment]
Hey, looking into it now.

**Comment by serban-nicusor-toptal** [comment]
Looks like that was a general issue as master and other branches were failing too.
Merging this into master should fix all of them.
@mitzimorris ready now.

**Pull request merged**
