### PR TITLE
Adding StanConnect to Events page

### PR DESCRIPTION
**Pull request by VeenDuco**
I've added StanConnect events to the Events page. 4 have own pages one links external. @jgabry as discussed I've done this via a PR. Could you check if I didn't screw up anything before it's merged?

### CODE REVIEW

**Comment by mitzimorris** [comment]
hi Duco,  those changes to the Gemfile.lock file might not fly on github - not sure.
on my machine, having problems testing your side locally

**Comment by mitzimorris** [comment]
OK, the answer is that we don't need to worry about changes to Gemfile and Gemfile.lock w/r/t Github pages hosting.
https://stackoverflow.com/questions/56261127/is-the-gemfile-lock-file-needed-in-a-jekyll-site-hosted-with-github-pages

I got this branch to build and it looks good.
in another PR, we should get rid of Gemfile and Gemfile.lock from repo.  Ruby and Jekyll are a real PITA!!!!

**Review by mitzimorris — APPROVED** [review]
LGTM!!!

**Comment by mitzimorris** [comment]
@VeenDuco - looked at why Travis build failed - definitely changes to Gemfile.lock are a problem.  if you revert that file to what's currently checked into master, that should work.

**Comment by jgabry** [comment]
Content looks good to me too. I don't understand the gemfile issues, so I would trust @mitzimorris on that.

**Comment by VeenDuco** [comment]
Thanks @mitzimorris for the review. I didn't get to build the website with the original gemlock file locally. It's a bit of a pain, so thank you for figuring it out! The Gemlock file is reverted back and the checks pass, so I'll merge.

**Comment by mitzimorris** [comment]
>  I didn't get to build the website with the original gemlock file locally. It's a bit of a pain, so thank you for figuring it out! The Gemlock file is reverted back and the checks pass, so I'll merge.

more than a bit of pain - it's totally stupid.  jekyll sucks.

**Pull request merged**
