### PR TITLE
Add planetary motion case study.

### PR DESCRIPTION
**Pull request by charlesm93**
## Summary

Add case study on Bayesian model of planetary motion. 

## Details

The point of this case study is to explore what to do when the posterior is multimodal and when ODE solving becomes very slow at some of the modes. This is a detailed description of the example in Section 11 of the Bayesian workflow paper: https://arxiv.org/pdf/2011.01808.pdf.

I wrote the markdown file using bookdown. For the html to render, we need two folders under `users/documentation/case-studies/`: `libs`, which contains files to render bookdown and `planetary_motion_files`, which stores the figures created by the md file.

### CODE REVIEW

**Comment by charlesm93** [comment]
@bbbales2 can you review this one?

**Comment by bbbales2** [comment]
@charlesm93 what is in the libs folder? I thought rstudio rendered htmls were always one file.

**Comment by charlesm93** [comment]
It's generated by bookdown. Without it, the html looks very clunky.

**Comment by bbbales2** [comment]
What I see has quite a bit of formatting: https://htmlpreview.github.io/?https://github.com/stan-dev/stan-dev.github.io/blob/2f98048b7176c9811697c301c2d77353e48d5de1/users/documentation/case-studies/planetary_motion.html , but I'm not sure if it's using some fallback rendering or something.

Here's a screenshot: 
planetary

Is it supposed to look different? (Btw it starts off looking like plain html but after a second or whatever it loads up all the fancy javascript.)

**Comment by bbbales2** [comment]
@charlesm93 Oh I see it's loading all that from github and it isn't included in the html. It should be fine to include these files, but they should be organized in a way so that they are only used with this case study and don't interfere with anyone else (who might also have a `libs/whatever` folder.

**Comment by bbbales2** [comment]
@mitzimorris there are a bunch of javascript dependencies (and a font and stuff) that goes along with this case study. How should we organize those?

Can we just put everything for this in a folder `users/documentation/case-studies/planetary_motion` (including all the js and whatnot) and call it a day?

**Comment by jgabry** [comment]
> Can we just put everything for this in a folder `users/documentation/case-studies/planetary_motion` (including all the js and whatnot) and call it a day?

That seems fine to me.

**Comment by bbbales2** [comment]
@jgabry @charlesm93 cool, let's do that then.

**Comment by charlesm93** [comment]
Done.

**Comment by bbbales2** [comment]
@charlesm93 it is live: https://mc-stan.org/users/documentation/case-studies.html

**Comment by jgabry** [comment]
Nice, this looks great, thanks @charlesm93!

**Pull request merged**
