### PR TITLE
Add ScalaStan link to their github.

### PR DESCRIPTION
**Pull request by seantalts**
Is it okay that we don't have a separate page for each piece of ScalaStan? I figure linking to a homepage makes a lot more sense than having a page for each interface if their homepage is somewhere else.

### CODE REVIEW

**Comment by syclik** [comment]
Looks good to me, but might want to check with @betanalpha. 

The only objection I could possibly see is that this would be the first interface that's listed that isn't maintained through the `stan-dev` github organization. I don't see `brms` listed. But I'm happy with it.

P.S. Feel free to merge on your own without a review. We don't really have any process on the website. I think just nothing too drastic without notification first.

**Comment by bob-carpenter** [comment]
> We don't really have any process on the website.

Yes, we do.  @breckbaldwin is in charge.  We decided to run it just like our other repos and put someone in charge of it to make final decisions.  Not quite a democratic open source process, but I find it helps to have someone to make a final decision and trust the heads of each of our repos to use good judgement and follow the informal policy:

>  nothing too drastic without notification first.

That's the informal policy.  Minor changes I wouldn't worry about just doing.  I certainly do things like push case studies, update links, etc.

>  I don't see brms listed.

We should probably add that, too.  I want to only add ones we've vetted in some sense and that provide higher-level interfaces to Stan.  I'd also be totally OK with creating a page (or multiple pages) of specialized interfaces.  @bgoodri has said in the past that people can just look at the dependencies on CRAN, but it may be useful to also duplicate this effort on our web site with some descriptions.  There's also the edstan page that Sophia et al. maintain.

**Comment by syclik** [comment]
Thanks for the corrections, Bob! It slipped my mind that Breck is now in charge of the website repo.

**Comment by syclik** [comment]
@seantalts, want to check with @breckbaldwin and get this merged?

**Comment by bob-carpenter** [comment]
I really thought it should have its own page.  I've also been trying to highlight links offsite with little grey parenthetical markers that say where they're going.  I'll reopen the issue.

**Comment by seantalts** [comment]
I asked Breck and he said it was fine, for the record. You also didn't say that you thought it should have its own page until just now.

I actually disagree and think having our own little landing pages for us to maintain for each of these projects that each have their own landing page is a duplication of effort and adds to confusion when they get out of sync.

**Comment by seantalts** [comment]
But also I don't care enough to do work either way towards it. I just added this because Ryan asked me to and I thought it would be good to link to another interface and no one else was doing it.

**Comment by bob-carpenter** [comment]
> On Jan 31, 2018, at 12:02 PM, seantalts <notifications@github.com> wrote:
> 
> I asked Breck and he said it was fine, for the record.

I wasn't complaining, just leaving to-do breadcrumbs --- adding a link's
great!

> You also didn't say that you thought it should have its own page until just now.

Sorry I didn't communicate that clearly---I had just assumed we were
talking about paralleling what'd been done with the other interfaces.

In many ways it's different since it's not an interface to the Stan
language.  So I'd have been inclined to put this under a different
heading and not group it with the others.

> I actually disagree and think having our own little landing pages for us to maintain for each of these projects that each have their own landing page is a duplication of effort and adds to confusion when they get out of sync.

Up to Breck.  I do feel strongly that the site should be consistent
in its treatment of the interfaces.  I'm OK with not having any internal
pages for any of the interfaces and just linking out to their own home
pages, whatever that means.

**Pull request merged**
