### PR TITLE
Updates to IRT case studies and tutorials

### PR DESCRIPTION
**Pull request by danielcfurr**
Fix misuse of monitor() in the case studies and update 2PL tutorial for changes to edstan package.

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Was there something you wanted code reviewed?  Otherwise, feel free to just merge yourself for the examples.

**Comment by danielcfurr** [comment]
Okay, I'll look into merging it myself. Thank you, Bob.

**Comment by danielcfurr** [comment]
Bob, do I have the necessary permissions to do the merge? I can't find the option to merge, so I'm guessing I may not have the permissions.

**Comment by syclik** [comment]
You should have permissions now.

**Comment by danielcfurr** [comment]
I do! Thank you.

**Pull request merged**
